import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-security-guard-overtime-invoice-audit",
  "engine": "recovery",
  "title": "Security Guard Overtime Invoice Audit",
  "shortTitle": "Security Guard Overtime Invoice Audit",
  "tagline": "Validate billed guard hours, overtime, holidays, post coverage, qualifications, and contractual bill rates.",
  "industry": "Security Services Cost Recovery",
  "buyer": "Enterprises, campuses, and property portfolios",
  "uiPort": 4725,
  "apiPort": 5725,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Security Guard Overtime Invoice Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits in one accountable workflow. Validate billed guard hours, overtime, holidays, post coverage, qualifications, and contractual bill rates.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Security Guard Overtime Invoice Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("security-contract-library","SGO01","Security contract library","Execute security contract library using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed security contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Security contract library Reference","text","SGO01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("post-order-registry","SGO02","Post order registry","Execute post order registry using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed post order registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Post order registry Reference","text","SGO02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("guard-credential-validation","SGO03","Guard credential validation","Execute guard credential validation using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed guard credential validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Guard credential validation Reference","text","SGO03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("schedule-ingestion","SGO04","Schedule ingestion","Execute schedule ingestion using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed schedule ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Schedule ingestion Reference","text","SGO04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("time-punch-matching","SGO05","Time punch matching","Execute time punch matching using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed time punch matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Time punch matching Reference","text","SGO05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("regular-hour-calculation","SGO06","Regular hour calculation","Execute regular hour calculation using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed regular hour calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Regular hour calculation Reference","text","SGO06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("overtime-responsibility","SGO07","Overtime responsibility","Execute overtime responsibility using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed overtime responsibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Overtime responsibility Reference","text","SGO07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("holiday-premium-audit","SGO08","Holiday premium audit","Execute holiday premium audit using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed holiday premium audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Holiday premium audit Reference","text","SGO08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("vacant-post-detection","SGO09","Vacant post detection","Execute vacant post detection using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed vacant post detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Vacant post detection Reference","text","SGO09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("supervisor-markup-control","SGO10","Supervisor markup control","Execute supervisor markup control using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed supervisor markup control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Supervisor markup control Reference","text","SGO10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("incident-coverage-validation","SGO11","Incident coverage validation","Execute incident coverage validation using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed incident coverage validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Incident coverage validation Reference","text","SGO11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("invoice-recalculation","SGO12","Invoice recalculation","Execute invoice recalculation using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Invoice recalculation Reference","text","SGO12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("vendor-dispute-workflow","SGO13","Vendor dispute workflow","Execute vendor dispute workflow using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed vendor dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Vendor dispute workflow Reference","text","SGO13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("credit-reconciliation","SGO14","Credit reconciliation","Execute credit reconciliation using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Credit reconciliation Reference","text","SGO14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]}),
feature("location-post-analytics","SGO15","Location post analytics","Execute location post analytics using security contracts, post orders, schedules, time punches, guard credentials, regular and overtime rates, holidays, vacancies, incidents, invoices, and credits.","Produce a governed location post analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Security Vendor / Post","text","Security Vendor / Post · Standard Case"],["caseReference","Location post analytics Reference","text","SGO15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1635000],["supportedAmount","Evidence-Supported Amount","currency",1373400],["domainDriver","Labor Charge","select","Regular",["Regular","Overtime","Holiday"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Security contract library case","Post order registry case","Guard credential validation case","Schedule ingestion case","Time punch matching case"]})
]);
